<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EnvToJson.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" />
		<PackageReference Include="JsonSchema.Net" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
		<PackageReference Include="System.CommandLine" />
	</ItemGroup>

</Project>
