name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GitBranch: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          packages: >
            bash
            build-base
            clang
            icu-libs
            krb5-libs
            libgcc
            libintl
            libssl1.1
            libstdc++
            zlib
            zlib-dev
      - name: setup cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: setup dotnet
        run: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --channel 8.0
          pwd
          dotnet --info
        shell: alpine.sh --root {0}
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
      - name: dotnet test
        run: dotnet test --configuration Release --no-restore --verbosity normal
      - name: dotnet publish
        run: dotnet publish --configuration Release
        shell: alpine.sh --root {0}
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/publish/EnvToJson/release/
